version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    restart: unless-stopped

networks:
  jenkins-network:
    driver: bridge